env:
  browser: true
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  sourceType: module
  tsconfigRootDir: ./
  ecmaVersion: 2020
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  - plugin:prettier/recommended
  - plugin:regexp/recommended
  - plugin:node/recommended
  - plugin:yml/standard
  - ./.imports.eslintrc.js
plugins:
  - "@typescript-eslint"
  - prettier
  - eslint-plugin-import-helpers
  - regexp
  - only-error
  - promise
  - xss
  - no-secrets
rules:
  semi: 2
  quotes:
    - error
    - single
    - avoidEscape: true
  arrow-parens:
    - error
    - as-needed
  yoda: error
  prettier/prettier:
    - error
    - endOfLine: auto
  node/no-unsupported-features/es-syntax: off
  node/no-extraneous-import:
    - error
    - allowModules:
      - '@jest/types'
      resolvePaths: []
      tryExtensions: []
  node/no-unpublished-import: off
  node/no-missing-import: off
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-unsafe-member-access": off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/ban-types": off
  regexp/no-obscure-range: off
settings:
  import/resolver:
    typescript: {}
    node:
      extensions:
        - .js
        - .ts

